### ISSUE TITLE
complexity instead of rating

### ISSUE THREAD

**Issue by mcmasterp** [GamerKingFaiz/bgg-collection#6]
Is it possible to show the complexity instead of rating?

**Comment by GamerKingFaiz** [comment]
Got the initial iteration of this working in a feature-branch. I decided to add a new column with weight/complexity because I believe they are both important.

Still need to work on the following before I deploy.
- [ ] Rate limiting the new API I had to query
- [ ] Styling the weight number to match the BGG theme

Hope to have this finished within this week!

**Comment by GamerKingFaiz** [comment]
This enhancement request has been addressed in #9! Changes are now live--enjoy. 🙂
